/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Clases.Conectar;
import static forms.login.txtusuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author e09am
 */
public class AccesoAdmin extends javax.swing.JFrame {
Conectar co = new Conectar();   
    Connection con = co.conexion();
    
    PreparedStatement ps = null;
    ResultSet rs;
    /**
     * Creates new form AccesoAdmin
     */
    public AccesoAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pswdadmin = new javax.swing.JPasswordField();
        btnveerify = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Por favor ingrese su contraseña:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        getContentPane().add(pswdadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, -1));

        btnveerify.setText("Verificar");
        btnveerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnveerifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnveerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("ADMINISTRACION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnveerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnveerifyActionPerformed
        
        
        int resultado  = 0; 
        int op = 0 ;
        String opcion;
        String pass= String.valueOf(pswdadmin.getPassword());
        String usuario = txtusuario.getText();
        String SQL = "SELECT * FROM tb_empleado where Nom_usuario='edwardarcem' AND Contraseña='"+pass+"'";
        
        try{
            Statement st = con.createStatement();
            ResultSet ra=st.executeQuery(SQL);
            
            if(ra.next()){
                resultado = 1;
                
                if(resultado == 1){
                    
                    opcion = JOptionPane.showInputDialog(null,"1. Registro de Empleados\n"
                            + "2.Ingreso de Productos");
                    op= Integer.parseInt(opcion);
                    
                    switch (op) {
                        case 1:
                            Registro_Empleados re = new Registro_Empleados();
                            re.setVisible(true);
                            this.dispose();
                            break;
                        case 2:
                            IngresoProductos in = new IngresoProductos();
                            in.setVisible(true);
                            this.dispose();
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Ingrese un dato válido");
                            break;
                    }
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "¡Por favor ingrese sus datos correctamente!", "Intente de nuevo", JOptionPane.WARNING_MESSAGE);
                txtusuario.setText("");
                pswdadmin.setText("");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error de Registro " + e.getMessage());
        }
    }//GEN-LAST:event_btnveerifyActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnveerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pswdadmin;
    // End of variables declaration//GEN-END:variables
}
